api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
#   limit zwracanych przez api encji w jednym obiekcie odpowiedzi. (paginacja)
#    defaults:
#        pagination_items_per_page: 15
