# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    'App\Serializer\AdminGroupsContextBuilder':
        decorates: 'api_platform.serializer.context_builder'
        arguments: [ '@App\Serializer\AdminGroupsContextBuilder.inner' ]

    'App\ApiPlatform\AutoGroupResourceMetadataFactory':
        decorates: 'api_platform.metadata.resource.metadata_factory'
        arguments: [ '@App\ApiPlatform\AutoGroupResourceMetadataFactory.inner' ]
        decoration_priority: -20

#   lines below arent needed anymore as DocumentController creates documentation with no problem
#    app.custom_authenticator:
#        class: App\Security\CustomJwtAuthenticator
#        parent: lexik_jwt_authentication.security.jwt_authenticator
#
    app.json_header_request_matcher:
        class: App\Security\JsonHeaderRequestMatcher

    'ApiPlatform\Core\Bridge\Symfony\Bundle\SwaggerUi\SwaggerUiContext': '@api_platform.swagger_ui.context'

    Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'

    App\DataProvider\ProductDataProvider:
        $itemDataProvider: '@api_platform.doctrine.orm.default.item_data_provider'
        $collectionDataProvider: '@api_platform.doctrine.orm.default.collection_data_provider'
#        $itemNormalizer: '@api_platform.jsonld.normalizer.item'

#    SONATA CLASSESS CONFIG
    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [ ~, App\Entity\Category, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }

    admin.subcategory:
        class: App\Admin\SubCategoryAdmin
        arguments: [ ~, App\Entity\SubCategory, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: SubCategory }

    admin.product:
        class: App\Admin\ProductAdmin
        arguments: [ ~, App\Entity\Product, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Product }

    admin.user:
        class: App\Admin\UserAdmin
        arguments: [ ~, App\Entity\User, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }

    admin.rate:
        class: App\Admin\RateAdmin
        arguments: [ ~, App\Entity\Rate, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Rate }













