<?php

namespace App\Validator;

use Symfony\Component\Validator\Constraint;

/**
 * @Annotation
 */
class IsMealTypeProper extends Constraint
{
    /*
     * Any public properties become valid options for the annotation.
     * Then, use these in your validator class.
     */
    public $message = 'You were trying to execute unauthorised action on Intake';

//    public function getTargets()
//    {
//        return self::CLASS_CONSTRAINT;
//    }
    public function validatedBy()
    {
        return \get_class($this).'Validator';
//        return parent::validatedBy(); // TODO: Change the autogenerated stub
    }
}
